#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-doxia-tools
Version  : 3
Release  : 1
URL      : https://github.com/apache/maven-doxia-tools/archive/doxia-tools-3.tar.gz
Source0  : https://github.com/apache/maven-doxia-tools/archive/doxia-tools-3.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-tools/3/doxia-tools-3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-doxia-tools-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-doxia-tools package.
Group: Data

%description data
data components for the mvn-doxia-tools package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-tools/3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-tools/3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-tools/3/doxia-tools-3.pom
